package app.rune

import com.google.gson.GsonBuilder
import org.bukkit.plugin.java.JavaPlugin
import java.nio.file.Files
import java.nio.file.Path

/**
 * Materialises the alias outputs declared via `rune.jsonc`:
 *   1. `runtime/aliases.json` -- a flat `{ name: dottedPath }` map read by
 *      the Node bootstrap, which binds each `globalThis[name] = resolve(path)`.
 *   2. `scripts/types/aliases.d.ts` -- TS declarations so the IDE knows
 *      that `inventory` is `typeof bukkit.inventory`, `mm` is
 *      `typeof kyori.adventure.text.minimessage`, etc.
 */
class AliasArtifacts(private val plugin: JavaPlugin) {

    private val gson = GsonBuilder().setPrettyPrinting().create()

    /**
     * @param runtimeAliases EVERY alias to install at runtime (user + plugin
     *   shortcuts). Written to aliases.json for the bootstrap to consume.
     * @param tsAliases  Only USER-declared aliases get typed via
     *   `const <name>: typeof <path>`. Plugin shortcuts are skipped here
     *   because each plugin's own `<alias>.d.ts` already declares
     *   `namespace <alias> { ... }` as a global -- duplicating it as a
     *   `const` would collapse it to `any` (the proxy `JavaPackage` type)
     *   AND collide with the namespace declaration.
     */
    fun write(
        runtimeDir: Path,
        scriptsTypesDir: Path,
        runtimeAliases: Map<String, String>,
        tsAliases: Map<String, String>,
    ) {
        writeRuntimeJson(runtimeDir, runtimeAliases)
        writeTypesDts(scriptsTypesDir, tsAliases)
    }

    private fun writeRuntimeJson(runtimeDir: Path, aliases: Map<String, String>) {
        Files.createDirectories(runtimeDir)
        val out = runtimeDir.resolve("aliases.json")
        Files.writeString(out, gson.toJson(aliases))
        plugin.logger.info("wrote ${aliases.size} alias(es) to $out")
    }

    private fun writeTypesDts(typesDir: Path, aliases: Map<String, String>) {
        Files.createDirectories(typesDir)
        val sb = StringBuilder()
        sb.appendLine("// Auto-generated by Rune from rune.jsonc `aliases`.")
        sb.appendLine("// Do NOT edit -- overwritten on every plugin enable.")
        sb.appendLine()
        sb.appendLine("export {};")
        sb.appendLine()
        sb.appendLine("declare global {")
        for ((name, path) in aliases) {
            // `typeof <dotted.path>` works in TS for any value/namespace
            // reachable from the global scope. We rely on the user's
            // tsconfig pulling in rune.d.ts + bukkit.d.ts so the path
            // resolves.
            sb.append("    const ").append(name).append(": typeof ").append(path).appendLine(";")
        }
        sb.appendLine("}")
        val out = typesDir.resolve("aliases.d.ts")
        Files.writeString(out, sb.toString())
        plugin.logger.info("wrote alias type declarations to $out")
    }
}
