package app.rune

import org.bukkit.plugin.java.JavaPlugin

/**
 * Emits `scripts/types/events.d.ts` whose `RuneEventMap` interface lists
 * every Bukkit / Paper event class on this server's classpath, mapping
 * the event's simple name to its generated interface type. Combined with
 * the existing typed overloads of `rune.on` and `EventHandler`, this
 * gives scripts full union autocomplete on event names + automatic
 * parameter typing on handler callbacks:
 *
 *   rune.on("PlayerJoinEvent", (e) => { ... });   // e: PlayerJoinEvent
 *
 *   @EventHandler("BlockBreakEvent")
 *   onBreak(e: BlockBreakEvent) { ... }            // typed param
 *
 * Uses the same EventDiscovery that the generic forwarder runs to find
 * the 430-ish classes, so the typed surface always matches what actually
 * dispatches at runtime.
 */
class EventTypeMapGenerator(private val plugin: JavaPlugin) {

    fun generate(): String {
        val events = try {
            EventDiscovery.discover(plugin)
        } catch (e: Throwable) {
            plugin.logger.warning("event-types: discovery failed: ${e.message}")
            return "// event discovery failed: ${e.message}\nexport {};\n"
        }
        // Group by simpleName so the map keys are unique. Bukkit + Paper
        // sometimes have classes whose simple names collide (rare but
        // possible across packages); on collision we keep the first seen
        // and skip the rest with a fine-log -- it's cosmetic, the runtime
        // dispatch is by simpleName anyway so the collision exists there
        // too.
        val seen = HashSet<String>()
        val entries = mutableListOf<Pair<String, String>>()
        for (cls in events) {
            val name = cls.simpleName
            if (name.isEmpty() || !seen.add(name)) continue
            entries.add(name to name)
        }

        val sb = StringBuilder()
        sb.appendLine("// Auto-generated by Rune from EventDiscovery.")
        sb.appendLine("// Do NOT edit -- overwritten on every plugin enable.")
        sb.appendLine("//")
        sb.appendLine("// Augments the hand-curated RuneEventMap in rune.d.ts with every")
        sb.appendLine("// Bukkit/Paper event class on the server classpath, so scripts get")
        sb.appendLine("//   * union-typed event names on rune.on() / @EventHandler()")
        sb.appendLine("//   * inferred parameter types on handler callbacks")
        sb.appendLine()
        sb.appendLine("export {};")
        sb.appendLine()
        sb.appendLine("declare global {")
        // Map-by-name (used internally for keyof unions).
        sb.appendLine("    interface RuneEventMap {")
        for ((name, ifaceName) in entries.sortedBy { it.first }) {
            sb.append("        ").append(name).append(": ").append(ifaceName).appendLine(";")
        }
        sb.appendLine("    }")
        sb.appendLine()
        // Branded-string enum-like value. `Events.X` is the string "X" at
        // runtime (a Proxy installed by the bootstrap returns property names
        // verbatim), but typed as EventKey<X> so the @EventHandler and
        // rune.on overloads can extract the event interface and contextually
        // type handler callbacks.
        sb.appendLine("    const Events: {")
        for ((name, ifaceName) in entries.sortedBy { it.first }) {
            sb.append("        readonly ").append(name)
                .append(": EventKey<").append(ifaceName).appendLine(">;")
        }
        sb.appendLine("    };")
        sb.appendLine("}")
        return sb.toString()
    }
}
