package app.rune

import io.github.classgraph.ClassGraph
import org.bukkit.plugin.java.JavaPlugin
import java.lang.reflect.Method
import java.lang.reflect.Modifier
import java.lang.reflect.ParameterizedType
import java.lang.reflect.Type
import java.lang.reflect.TypeVariable
import java.lang.reflect.WildcardType
import java.util.ArrayDeque

/**
 * Reflects the Bukkit / Paper / Adventure class surface that's actually
 * loaded on this server and emits a `bukkit.d.ts` containing TypeScript
 * interface declarations for each class.
 *
 * Strategy:
 *   * Start from a seed of the API entry-point classes (Player, Block,
 *     World, ItemStack, ...) plus a handful of supporting types.
 *   * Walk the transitive closure of each seed's superclass + interface
 *     graph, restricted to packages we expose (`org.bukkit.**`,
 *     `io.papermc.paper.**`, `net.kyori.adventure.**`).
 *   * Emit each class as a TS `interface` whose `extends` list mirrors the
 *     Java inheritance graph, with every public *declared* method.
 *
 * Interface merging means these interfaces compose with the hand-curated
 * `rune.d.ts`: the snapshot fields (`name`, `uuid`, `x`, ...) live there;
 * the reflected methods live here.
 */
class TsSurfaceGenerator(private val plugin: JavaPlugin) {

    private val seedNames: List<String> = listOf(
        // entity hierarchy
        "org.bukkit.entity.Player",
        "org.bukkit.entity.HumanEntity",
        "org.bukkit.entity.LivingEntity",
        "org.bukkit.entity.Entity",
        "org.bukkit.entity.Mob",
        "org.bukkit.entity.Damageable",
        "org.bukkit.entity.Item",
        "org.bukkit.entity.Projectile",
        "org.bukkit.entity.ArmorStand",
        "org.bukkit.entity.EntityType",
        // blocks
        "org.bukkit.block.Block",
        "org.bukkit.block.BlockState",
        "org.bukkit.block.Container",
        "org.bukkit.block.Sign",
        "org.bukkit.block.data.BlockData",
        // world
        "org.bukkit.World",
        "org.bukkit.Location",
        "org.bukkit.Chunk",
        "org.bukkit.Server",
        "org.bukkit.Bukkit",
        "org.bukkit.OfflinePlayer",
        "org.bukkit.GameMode",
        "org.bukkit.WorldBorder",
        // inventory
        "org.bukkit.inventory.ItemStack",
        "org.bukkit.inventory.Inventory",
        "org.bukkit.inventory.PlayerInventory",
        "org.bukkit.inventory.ItemMeta",
        // commands
        "org.bukkit.command.Command",
        "org.bukkit.command.CommandSender",
        // scheduler
        "org.bukkit.scheduler.BukkitScheduler",
        "org.bukkit.scheduler.BukkitTask",
        // enums-as-classes
        "org.bukkit.Material",
        "org.bukkit.Particle",
        "org.bukkit.Sound",
        "org.bukkit.NamespacedKey",
        "org.bukkit.Color",
        // util
        "org.bukkit.util.Vector",
        "org.bukkit.util.BlockVector",
        "org.bukkit.util.BoundingBox",
        // permissions
        "org.bukkit.permissions.Permissible",
        "org.bukkit.permissions.Permission",
        "org.bukkit.permissions.ServerOperator",
        // persistence
        "org.bukkit.persistence.PersistentDataContainer",
        "org.bukkit.persistence.PersistentDataType",
        "org.bukkit.persistence.PersistentDataHolder",
        // adventure
        "net.kyori.adventure.text.Component",
        "net.kyori.adventure.audience.Audience",
    )

    fun generate(): String {
        val classes = enumerateClasses().filter { it.enclosingClass == null }
        val known = classes.toSet()
        val sb = StringBuilder()

        sb.appendLine("// Auto-generated by Rune from this server's live classpath.")
        sb.appendLine("// Do NOT edit -- overwritten on every plugin enable.")
        sb.appendLine("// Merges with rune.d.ts via TypeScript interface merging.")
        sb.appendLine()
        sb.appendLine("export {};")
        sb.appendLine()
        sb.appendLine("declare global {")

        // Pass 1: flat instance interfaces (existing shape; rune.d.ts merges
        // with these so user-script type annotations like `let p: Player` work).
        for (clazz in classes) {
            try {
                emitInterface(sb, clazz, known)
            } catch (e: Throwable) {
                plugin.logger.fine("ts-gen: skipped interface ${clazz.name}: ${e.message}")
            }
        }

        // Pass 2: nested-namespace value declarations. For each package root
        // we map (`bukkit` = `org.bukkit`, `paper` = `io.papermc.paper`,
        // `kyori` = `net.kyori`), emit a TS namespace whose `const`s give
        // each class a constructor + static surface. This is what makes
        //   `new bukkit.inventory.ItemStack(material)`
        // typecheck.
        try {
            emitNamespaceTree(sb, classes, known, ::mapToTsPath)
        } catch (e: Throwable) {
            plugin.logger.warning("ts-gen: namespace tree emission failed: ${e.message}")
        }

        sb.appendLine("}")
        return sb.toString()
    }

    /**
     * Emit a per-plugin `<alias>.d.ts` for a Bukkit plugin dep declared in
     * `rune.jsonc`. ClassGraph scans the plugin's own classloader limited
     * to its declared package; every class found gets emitted as a flat
     * interface PLUS a namespaced const value (constructor + statics) the
     * same way the core generator handles Bukkit/Paper/Kyori.
     */
    fun generateForPlugin(
        loader: ClassLoader,
        packageRoot: String,
        tsAlias: String,
    ): String {
        val classes = try {
            ClassGraph()
                .overrideClassLoaders(loader)
                .acceptPackages(packageRoot)
                .enableClassInfo()
                .scan()
                .use { result ->
                    result.allClasses
                        .mapNotNull {
                            try { it.loadClass() } catch (_: Throwable) { null }
                        }
                        .filter {
                            !it.isAnonymousClass && !it.isLocalClass &&
                                it.enclosingClass == null
                        }
                }
        } catch (e: Throwable) {
            plugin.logger.warning("ts-gen[$tsAlias]: classpath scan failed: ${e.message}")
            return "// ts-gen failed for $tsAlias: ${e.message}\nexport {};\n"
        }
        if (classes.isEmpty()) {
            return "// ts-gen: no classes found under $packageRoot\nexport {};\n"
        }
        val known = classes.toSet()
        val sb = StringBuilder()
        sb.appendLine("// Auto-generated by Rune for plugin dependency '$tsAlias' ($packageRoot).")
        sb.appendLine("// Do NOT edit -- overwritten on every plugin enable.")
        sb.appendLine()
        sb.appendLine("export {};")
        sb.appendLine()
        sb.appendLine("declare global {")
        // Flat instance interfaces (named globally so they merge w/ rune.d.ts).
        for (clazz in classes) {
            try {
                emitInterface(sb, clazz, known)
            } catch (e: Throwable) {
                plugin.logger.fine("ts-gen[$tsAlias]: skipped interface ${clazz.name}: ${e.message}")
            }
        }
        // Namespace value tree under <tsAlias>.*.
        val mapper: (String) -> String? = { fqn ->
            if (fqn.startsWith("$packageRoot.")) "$tsAlias." + fqn.removePrefix("$packageRoot.")
            else null
        }
        try {
            emitNamespaceTree(sb, classes, known, mapper)
        } catch (e: Throwable) {
            plugin.logger.warning("ts-gen[$tsAlias]: namespace emission failed: ${e.message}")
        }
        sb.appendLine("}")
        return sb.toString()
    }

    // ---------------------------------------------------------------------
    // Namespace tree
    // ---------------------------------------------------------------------

    private class TreeNode {
        val children: MutableMap<String, TreeNode> = linkedMapOf()
        val classes: MutableMap<String, Class<*>> = linkedMapOf()
    }

    /** Map an FQN to a TS dotted path, or null if outside our known roots. */
    private fun mapToTsPath(fqn: String): String? = when {
        fqn.startsWith("org.bukkit.") -> "bukkit." + fqn.removePrefix("org.bukkit.")
        fqn.startsWith("io.papermc.paper.") -> "paper." + fqn.removePrefix("io.papermc.paper.")
        fqn.startsWith("net.kyori.") -> "kyori." + fqn.removePrefix("net.kyori.")
        else -> null
    }

    private fun emitNamespaceTree(
        sb: StringBuilder,
        classes: List<Class<*>>,
        known: Set<Class<*>>,
        mapper: (String) -> String?,
    ) {
        val root = TreeNode()
        for (clazz in classes) {
            val tsPath = mapper(clazz.name) ?: continue
            val parts = tsPath.split('.')
            if (parts.size < 2) continue
            var node = root
            for (i in 0 until parts.size - 1) {
                node = node.children.getOrPut(parts[i]) { TreeNode() }
            }
            node.classes[parts.last()] = clazz
        }
        for ((name, child) in root.children) {
            emitNamespace(sb, name, child, known, indent = 1)
        }
    }

    private fun emitNamespace(sb: StringBuilder, name: String, node: TreeNode,
                              known: Set<Class<*>>, indent: Int) {
        val pad = "    ".repeat(indent)
        sb.append(pad).append("namespace ").append(name).appendLine(" {")
        for ((cname, clazz) in node.classes) {
            try {
                emitClassValue(sb, cname, clazz, known, indent + 1)
            } catch (e: Throwable) {
                plugin.logger.fine("ts-gen: skipped value ${clazz.name}: ${e.message}")
            }
        }
        for ((childName, childNode) in node.children) {
            emitNamespace(sb, childName, childNode, known, indent + 1)
        }
        sb.append(pad).appendLine("}")
        sb.appendLine()
    }

    /**
     * Emit one class's value side inside its enclosing namespace:
     *
     *   type Foo = globalThis.Foo;                 // alias to the flat interface
     *   const Foo: {
     *     new(args): Foo;                          // every public ctor
     *     staticMethod(arg): RetType;              // every public static method
     *     readonly STATIC_FIELD: FieldType;        // public static fields
     *     [member: string]: any;                   // escape hatch
     *   };
     *
     * For interfaces / abstract classes (no public ctors) the `new` signatures
     * are simply omitted.
     */
    private fun emitClassValue(sb: StringBuilder, simpleName: String, clazz: Class<*>,
                               known: Set<Class<*>>, indent: Int) {
        val pad = "    ".repeat(indent)
        val inner = "    ".repeat(indent + 1)

        // Type alias so `bukkit.inventory.ItemStack` works as a TYPE (the
        // flat interface emitted in pass 1 stays at the global scope; we
        // re-export it here under the namespaced name).
        sb.append(pad).append("type ").append(simpleName)
            .append(" = globalThis.").append(simpleName).appendLine(";")

        sb.append(pad).append("const ").append(simpleName).appendLine(": {")

        // Public constructors -> overloaded `new` signatures.
        val ctors = clazz.declaredConstructors.filter {
            Modifier.isPublic(it.modifiers) && !it.isSynthetic
        }
        for (ctor in ctors) {
            val params = ctor.parameters.mapIndexed { i, p ->
                val pname = escapeIdent(if (p.isNamePresent) p.name else "arg$i")
                "$pname: ${tsType(p.parameterizedType, known)}"
            }.joinToString(", ")
            sb.append(inner).append("new(").append(params).append("): ").append(simpleName).appendLine(";")
        }

        // Public static methods.
        val staticMethods = clazz.declaredMethods.filter {
            Modifier.isPublic(it.modifiers) &&
                Modifier.isStatic(it.modifiers) &&
                !it.isSynthetic && !it.isBridge
        }.sortedBy { it.name }
        for (m in staticMethods) {
            sb.append(inner).appendLine(formatMethod(m, known))
        }

        // Public static fields (enum values, NamespacedKey.MINECRAFT, ...).
        val staticFields = clazz.declaredFields.filter {
            Modifier.isPublic(it.modifiers) &&
                Modifier.isStatic(it.modifiers) &&
                !it.isSynthetic
        }.sortedBy { it.name }
        for (f in staticFields) {
            val ftype = tsType(f.genericType, known)
            sb.append(inner).append("readonly ").append(escapeIdent(f.name))
                .append(": ").append(ftype).appendLine(";")
        }

        // Escape hatch: any other static accessor we missed.
        sb.append(inner).appendLine("[member: string]: any;")
        sb.append(pad).appendLine("};")
    }

    private fun enumerateClasses(): List<Class<*>> {
        val seen = LinkedHashSet<Class<*>>()
        val queue = ArrayDeque<Class<*>>()

        // Seed set 1: hand-picked entry points (keeps these on top of the
        // emit order so the most-used classes are first in bukkit.d.ts).
        for (name in seedNames) {
            loadClass(name)?.let { queue.add(it) }
        }

        // Seed set 2: every public class under the exposed packages.
        // ClassGraph walks the actual Paper classpath, so we get
        // ShapedRecipe, MerchantRecipe, ChunkSnapshot, and the thousands
        // of other surface types without having to maintain a hand-list.
        try {
            val scanned = ClassGraph()
                .overrideClassLoaders(plugin.javaClass.classLoader)
                .acceptPackages(
                    "org.bukkit",
                    "io.papermc.paper",
                    "com.destroystokyo.paper",
                    "net.kyori.adventure",
                )
                .enableClassInfo()
                .scan()
            scanned.use { result ->
                for (info in result.allClasses) {
                    val cls = try {
                        info.loadClass()
                    } catch (_: Throwable) {
                        continue
                    }
                    if (cls.isAnonymousClass || cls.isLocalClass) continue
                    if (cls.enclosingClass != null) continue  // skip nested
                    if (!shouldExpose(cls)) continue
                    queue.add(cls)
                }
            }
        } catch (e: Throwable) {
            plugin.logger.warning("ts-gen: classpath scan failed, falling back to seed-only: ${e.message}")
        }

        // BFS over the union: skip duplicates, pull supers + interfaces +
        // referenced method/parameter types so signatures resolve.
        while (queue.isNotEmpty()) {
            val c = queue.removeFirst()
            if (!seen.add(c)) continue
            c.superclass?.let {
                if (shouldExpose(it) && it !in seen) queue.add(it)
            }
            for (iface in c.interfaces) {
                if (shouldExpose(iface) && iface !in seen) queue.add(iface)
            }
            for (m in publicInstanceMethods(c)) {
                queueRelevantTypes(m.genericReturnType, seen, queue)
                for (p in m.genericParameterTypes) {
                    queueRelevantTypes(p, seen, queue)
                }
            }
        }
        return seen.toList()
    }

    private fun queueRelevantTypes(type: Type, seen: Set<Class<*>>, queue: ArrayDeque<Class<*>>) {
        when (type) {
            is Class<*> -> {
                if (shouldExpose(type) && type !in seen) queue.add(type)
                if (type.isArray) queueRelevantTypes(type.componentType, seen, queue)
            }
            is ParameterizedType -> {
                queueRelevantTypes(type.rawType, seen, queue)
                for (arg in type.actualTypeArguments) queueRelevantTypes(arg, seen, queue)
            }
            is WildcardType -> {
                type.upperBounds.forEach { queueRelevantTypes(it, seen, queue) }
            }
            else -> {}
        }
    }

    private fun shouldExpose(clazz: Class<*>): Boolean {
        val name = clazz.name
        if (clazz == Any::class.java || clazz == Object::class.java) return false
        return name.startsWith("org.bukkit.") ||
            name.startsWith("io.papermc.paper.") ||
            name.startsWith("com.destroystokyo.paper.") ||
            name.startsWith("net.kyori.adventure.")
    }

    private fun emitInterface(sb: StringBuilder, clazz: Class<*>, known: Set<Class<*>>) {
        sb.append("    interface ").append(clazz.simpleName)

        val extends = mutableListOf<String>()
        clazz.superclass?.takeIf { it in known }?.let { extends.add(it.simpleName) }
        for (iface in clazz.interfaces) {
            if (iface in known) extends.add(iface.simpleName)
        }
        // RuneRef snaps __ref / __class onto every Bukkit-backed object.
        extends.add("RuneRef")

        sb.append(" extends ").append(extends.distinct().joinToString(", "))
        sb.appendLine(" {")

        val methods = publicInstanceMethods(clazz).sortedBy { it.name }
        for (method in methods) {
            sb.append("        ").appendLine(formatMethod(method, known))
        }

        // Index signature lets the proxy forward any unlisted method too.
        sb.appendLine("        [method: string]: any;")
        sb.appendLine("    }")
        sb.appendLine()
    }

    private fun publicInstanceMethods(clazz: Class<*>): List<Method> {
        // Use `methods` (inherited + declared) rather than `declaredMethods`
        // so each interface re-emits the full overload set of every method
        // name it carries. TypeScript's overload-merging rule replaces a
        // parent's overloads when the child declares ANY signature with
        // the same name -- without this, e.g. MiniMessage.deserialize(s,
        // tagResolver) hides ComponentSerializer.deserialize(s), and
        // scripts calling `mm.deserialize("...")` get a type error.
        //
        // Dedupe by (name, paramTypes) so identical re-declarations
        // (interfaces multiply inheriting the same method) don't bloat
        // the output more than necessary.
        return clazz.methods
            .filter {
                Modifier.isPublic(it.modifiers) &&
                    !Modifier.isStatic(it.modifiers) &&
                    !it.isSynthetic &&
                    !it.isBridge &&
                    it.declaringClass != Object::class.java
            }
            .distinctBy { Pair(it.name, it.parameterTypes.toList()) }
    }

    private fun formatMethod(m: Method, known: Set<Class<*>>): String {
        val name = escapeIdent(m.name)
        val params = m.parameters.mapIndexed { i, p ->
            val pname = escapeIdent(if (p.isNamePresent) p.name else "arg$i")
            "$pname: ${tsType(p.parameterizedType, known)}"
        }.joinToString(", ")
        val ret = tsType(m.genericReturnType, known)
        return "$name($params): $ret;"
    }

    private fun tsType(type: Type, known: Set<Class<*>>): String = when (type) {
        is Class<*> -> tsTypeForClass(type, known)
        is ParameterizedType -> {
            val raw = type.rawType as? Class<*>
            when {
                raw == null -> "any"
                Collection::class.java.isAssignableFrom(raw) -> {
                    val arg = type.actualTypeArguments.firstOrNull()
                    "${arg?.let { tsType(it, known) } ?: "any"}[]"
                }
                Map::class.java.isAssignableFrom(raw) -> "Record<string, any>"
                else -> tsTypeForClass(raw, known)
            }
        }
        is WildcardType -> type.upperBounds.firstOrNull()
            ?.let { tsType(it, known) } ?: "any"
        is TypeVariable<*> -> "any"
        else -> "any"
    }

    private fun tsTypeForClass(clazz: Class<*>, known: Set<Class<*>>): String = when {
        clazz == Void.TYPE || clazz == java.lang.Void::class.java -> "void"
        clazz == String::class.java || clazz == CharSequence::class.java -> "string"
        clazz == java.lang.Boolean.TYPE || clazz == java.lang.Boolean::class.java -> "boolean"
        clazz.isPrimitive -> "number"
        clazz in NUMERIC_BOXED -> "number"
        clazz == java.util.UUID::class.java -> "string"
        clazz.isArray -> "${tsTypeForClass(clazz.componentType, known)}[]"
        clazz in known -> clazz.simpleName
        clazz == java.lang.Object::class.java -> "any"
        clazz.isEnum -> "string"
        else -> "any"
    }

    private fun loadClass(name: String): Class<*>? = try {
        Class.forName(name, false, plugin.javaClass.classLoader)
    } catch (_: ClassNotFoundException) {
        plugin.logger.fine("ts-gen: class not on classpath: $name")
        null
    }

    private fun escapeIdent(s: String): String =
        if (s in TS_RESERVED) "_$s" else s

    private companion object {
        val NUMERIC_BOXED: Set<Class<*>> = setOf(
            java.lang.Integer::class.java,
            java.lang.Long::class.java,
            java.lang.Short::class.java,
            java.lang.Byte::class.java,
            java.lang.Float::class.java,
            java.lang.Double::class.java,
            java.lang.Number::class.java,
        )

        // TS reserved words that can't be parameter names or method names
        // without quoting/escaping. Conservative list.
        val TS_RESERVED: Set<String> = setOf(
            "break", "case", "catch", "class", "const", "continue", "debugger",
            "default", "delete", "do", "else", "enum", "export", "extends",
            "false", "finally", "for", "function", "if", "import", "in",
            "instanceof", "new", "null", "return", "super", "switch", "this",
            "throw", "true", "try", "typeof", "var", "void", "while", "with",
            "yield", "interface", "type",
        )
    }
}
