//! `rune init` — scaffold a new Rune project.

use std::path::Path;

use anyhow::{Context, Result, bail};
use console::style;

use crate::cli::{InitArgs, Language};

pub async fn run(args: InitArgs) -> Result<()> {
    let dir = args.dir.canonicalize().or_else(|_| -> Result<_> {
        std::fs::create_dir_all(&args.dir)
            .with_context(|| format!("creating {}", args.dir.display()))?;
        Ok(args.dir.canonicalize()?)
    })?;

    let name = args.name.unwrap_or_else(|| derive_name(&dir));
    crate::config::validate_name(&name)
        .with_context(|| format!("derived name {name:?} is not a valid Rune name"))?;

    let files = [
        ("rune.toml", rune_toml(&name, args.language)),
        (
            match args.language {
                Language::Typescript => "src/index.ts",
                Language::Wasm => "src/main.rs",
            },
            entry_template(args.language),
        ),
        (".runeignore", runeignore_template().to_string()),
        ("README.md", readme_template(&name)),
    ];

    for (rel, contents) in files {
        let path = dir.join(rel);
        if path.exists() && !args.force {
            bail!(
                "{} already exists. Re-run with --force to overwrite.",
                path.display()
            );
        }
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&path, contents)
            .with_context(|| format!("writing {}", path.display()))?;
        println!("  {} {}", style("created").green(), rel);
    }

    println!();
    println!("{} {}", style("Rune scaffolded:").green().bold(), name);
    println!(
        "  Next: {}",
        style(format!("cd {} && rune pack", args.dir.display())).cyan(),
    );
    Ok(())
}

fn derive_name(dir: &Path) -> String {
    let raw = dir
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("my-rune")
        .to_lowercase();
    // Replace whitespace + invalid chars with `-`. Keeps the user out of
    // the validator's red zone when their folder is "My Project".
    let mut out = String::with_capacity(raw.len());
    for c in raw.chars() {
        if c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-' || c == '_' {
            out.push(c);
        } else {
            out.push('-');
        }
    }
    let trimmed = out.trim_matches('-').to_string();
    if trimmed.is_empty() { "my-rune".to_string() } else { trimmed }
}

fn rune_toml(name: &str, language: Language) -> String {
    let entry = match language {
        Language::Typescript => "src/index.ts",
        Language::Wasm => "src/main.rs",
    };
    format!(
        r#"# Generated by `rune init`. Edit freely.
#
# Add a scope by prefixing the name with `@<your-username>/` once you've
# claimed a username in the Runebook dashboard. Unscoped names are
# first-come-first-served on Runebook.

name    = "{name}"
version = "0.1.0"
language = "{lang}"
entry   = "{entry}"

description = "TODO: one-line summary of what this Rune does."
license     = "MIT"

# What gets packed. Defaults below ship a sane v1; tweak as you go.
[publish]
include = ["src/**", "rune.toml", "README*", "LICENSE*"]
exclude = ["src/**/*.test.ts"]

# What this Rune needs from the host. Operators see this on the install
# page and decide whether to trust the install — keep the list minimal.
[capabilities]
required = ["host:bukkit"]

# Other Runes this one depends on. Semver-resolved at install time.
[dependencies]
# "@rune/sdk" = "^0.4.0"
"#,
        lang = language.manifest_value(),
    )
}

fn entry_template(language: Language) -> String {
    match language {
        Language::Typescript => r#"// Entry point for your Rune.
//
// Decorators (`@Listener`, `@EventHandler`, `@Command`, ...) and the
// `rune` global are wired automatically by the Rune runtime. See the
// platform docs at https://runemc.dev/docs for the full surface.

console.info("hello from rune!");
"#
        .to_string(),
        Language::Wasm => r#"// Entry point for your Rune (Wasm target).
//
// Build with `cargo build --target wasm32-unknown-unknown --release`
// or `wasm-pack build`. The Rune runtime loads the resulting `.wasm`.

#[no_mangle]
pub extern "C" fn on_load() {
    // Wasm host-API wiring goes here.
}
"#
        .to_string(),
    }
}

fn runeignore_template() -> &'static str {
    // .runeignore reads like .gitignore. Most of the default-deny lives
    // in code (see ignore_filter.rs); this is just the per-project
    // additions a typical author wants.
    r#"# Patterns here are excluded from `rune pack` and `rune publish`.
# Same syntax as .gitignore.

# Local notes and scratch work.
NOTES.md
TODO.md
.scratch/

# Editor / IDE leftovers.
.idea/
.vscode/

# Build artifacts you might keep alongside source.
dist/
out/
"#
}

fn readme_template(name: &str) -> String {
    format!(
        "# {name}\n\n\
         TODO: describe what this Rune does, how operators install it, \
         and what capabilities they're trusting it with.\n\n\
         ## Install\n\n\
         ```sh\n\
         rune add {name}\n\
         ```\n",
    )
}
